// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="saveSrcDest_kernel_saveSrcDest_kernel,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu280-fsvh2892-2L-e,HLS_INPUT_CLOCK=2.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=1.305000,HLS_SYN_LAT=3,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=166,HLS_SYN_LUT=418,HLS_VERSION=2021_2}" *)

module saveSrcDest_kernel (
        ap_local_block,
        ap_local_deadlock,
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        user_extern_in_TVALID,
        user_extern_out_TREADY,
        user_extern_in_TDATA,
        user_extern_in_TREADY,
        user_extern_out_TDATA,
        user_extern_out_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

output   ap_local_block;
output   ap_local_deadlock;
input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   user_extern_in_TVALID;
input   user_extern_out_TREADY;
input  [63:0] user_extern_in_TDATA;
output   user_extern_in_TREADY;
output  [63:0] user_extern_out_TDATA;
output   user_extern_out_TVALID;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] first_load_reg_328;
reg   [0:0] first_load_reg_328_pp0_iter1_reg;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
reg   [0:0] first_load_reg_328_pp0_iter2_reg;
wire    regslice_both_user_extern_out_U_apdone_blk;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_state4_io;
reg    ap_block_pp0_stage0_subdone;
reg   [7:0] curr_V;
reg   [0:0] first;
reg   [7:0] prev_V;
reg   [6:0] saved_addresses_V_1_address0;
reg    saved_addresses_V_1_ce0;
reg    saved_addresses_V_1_we0;
reg   [31:0] saved_addresses_V_1_d0;
reg   [6:0] saved_addresses_V_1_address1;
reg    saved_addresses_V_1_ce1;
wire   [31:0] saved_addresses_V_1_q1;
reg   [6:0] saved_addresses_V_0_address0;
reg    saved_addresses_V_0_ce0;
reg    saved_addresses_V_0_we0;
reg   [31:0] saved_addresses_V_0_d0;
reg   [6:0] saved_addresses_V_0_address1;
reg    saved_addresses_V_0_ce1;
wire   [31:0] saved_addresses_V_0_q1;
reg    user_extern_in_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    user_extern_out_TDATA_blk_n;
wire   [0:0] first_load_load_fu_218_p1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] trunc_ln31_fu_232_p1;
reg   [0:0] trunc_ln31_reg_332;
reg   [0:0] trunc_ln31_reg_332_pp0_iter1_reg;
reg   [6:0] lshr_ln2_reg_338;
reg   [6:0] lshr_ln3_reg_343;
wire   [63:0] p_s_fu_316_p3;
wire   [63:0] zext_ln22_fu_190_p1;
wire   [63:0] zext_ln23_fu_212_p1;
wire   [63:0] zext_ln31_fu_292_p1;
wire   [63:0] zext_ln32_fu_297_p1;
wire   [7:0] add_ln885_fu_222_p2;
wire   [7:0] add_ln885_1_fu_268_p2;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] trunc_ln22_fu_176_p1;
wire   [31:0] tmp_src_V_fu_154_p1;
wire   [6:0] lshr_ln_fu_180_p4;
wire   [7:0] ret_fu_196_p2;
wire   [6:0] lshr_ln1_fu_202_p4;
wire   [7:0] ret_1_fu_246_p2;
wire   [31:0] tmp_dest_V_1_fu_309_p3;
wire   [31:0] tmp_src_V_1_fu_302_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to2;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_user_extern_in_U_apdone_blk;
wire   [63:0] user_extern_in_TDATA_int_regslice;
wire    user_extern_in_TVALID_int_regslice;
reg    user_extern_in_TREADY_int_regslice;
wire    regslice_both_user_extern_in_U_ack_in;
reg   [63:0] user_extern_out_TDATA_int_regslice;
reg    user_extern_out_TVALID_int_regslice;
wire    user_extern_out_TREADY_int_regslice;
wire    regslice_both_user_extern_out_U_vld_out;
reg    ap_condition_121;
reg    ap_condition_353;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 curr_V = 8'd0;
#0 first = 1'd1;
#0 prev_V = 8'd0;
end

saveSrcDest_kernel_saved_addresses_V_1_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
saved_addresses_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(saved_addresses_V_1_address0),
    .ce0(saved_addresses_V_1_ce0),
    .we0(saved_addresses_V_1_we0),
    .d0(saved_addresses_V_1_d0),
    .address1(saved_addresses_V_1_address1),
    .ce1(saved_addresses_V_1_ce1),
    .q1(saved_addresses_V_1_q1)
);

saveSrcDest_kernel_saved_addresses_V_1_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
saved_addresses_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(saved_addresses_V_0_address0),
    .ce0(saved_addresses_V_0_ce0),
    .we0(saved_addresses_V_0_we0),
    .d0(saved_addresses_V_0_d0),
    .address1(saved_addresses_V_0_address1),
    .ce1(saved_addresses_V_0_ce1),
    .q1(saved_addresses_V_0_q1)
);

saveSrcDest_kernel_regslice_both #(
    .DataWidth( 64 ))
regslice_both_user_extern_in_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(user_extern_in_TDATA),
    .vld_in(user_extern_in_TVALID),
    .ack_in(regslice_both_user_extern_in_U_ack_in),
    .data_out(user_extern_in_TDATA_int_regslice),
    .vld_out(user_extern_in_TVALID_int_regslice),
    .ack_out(user_extern_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_user_extern_in_U_apdone_blk)
);

saveSrcDest_kernel_regslice_both #(
    .DataWidth( 64 ))
regslice_both_user_extern_out_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(user_extern_out_TDATA_int_regslice),
    .vld_in(user_extern_out_TVALID_int_regslice),
    .ack_in(user_extern_out_TREADY_int_regslice),
    .data_out(user_extern_out_TDATA),
    .vld_out(regslice_both_user_extern_out_U_vld_out),
    .ack_out(user_extern_out_TREADY),
    .apdone_blk(regslice_both_user_extern_out_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1) & (first_load_load_fu_218_p1 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1) & (first_load_load_fu_218_p1 == 1'd0)))) begin
        curr_V <= add_ln885_fu_222_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1) & (first_load_load_fu_218_p1 == 1'd1))) begin
        first <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        first_load_reg_328 <= first;
        first_load_reg_328_pp0_iter1_reg <= first_load_reg_328;
        trunc_ln31_reg_332_pp0_iter1_reg <= trunc_ln31_reg_332;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        first_load_reg_328_pp0_iter2_reg <= first_load_reg_328_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (first_load_load_fu_218_p1 == 1'd0))) begin
        lshr_ln2_reg_338 <= {{prev_V[7:1]}};
        lshr_ln3_reg_343 <= {{ret_1_fu_246_p2[7:1]}};
        trunc_ln31_reg_332 <= trunc_ln31_fu_232_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1) & (first_load_load_fu_218_p1 == 1'd0))) begin
        prev_V <= add_ln885_1_fu_268_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0 == 1'b1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (ap_start == 1'b0))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_121)) begin
        if ((trunc_ln22_fu_176_p1 == 1'd1)) begin
            saved_addresses_V_0_address0 = zext_ln23_fu_212_p1;
        end else if ((trunc_ln22_fu_176_p1 == 1'd0)) begin
            saved_addresses_V_0_address0 = zext_ln22_fu_190_p1;
        end else begin
            saved_addresses_V_0_address0 = 'bx;
        end
    end else begin
        saved_addresses_V_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_353)) begin
        if ((trunc_ln31_reg_332 == 1'd1)) begin
            saved_addresses_V_0_address1 = zext_ln32_fu_297_p1;
        end else if ((trunc_ln31_reg_332 == 1'd0)) begin
            saved_addresses_V_0_address1 = zext_ln31_fu_292_p1;
        end else begin
            saved_addresses_V_0_address1 = 'bx;
        end
    end else begin
        saved_addresses_V_0_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1) & (trunc_ln22_fu_176_p1 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1) & (trunc_ln22_fu_176_p1 == 1'd0)))) begin
        saved_addresses_V_0_ce0 = 1'b1;
    end else begin
        saved_addresses_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (first_load_reg_328 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln31_reg_332 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (first_load_reg_328 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln31_reg_332 == 1'd0)))) begin
        saved_addresses_V_0_ce1 = 1'b1;
    end else begin
        saved_addresses_V_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_121)) begin
        if ((trunc_ln22_fu_176_p1 == 1'd1)) begin
            saved_addresses_V_0_d0 = {{user_extern_in_TDATA_int_regslice[63:32]}};
        end else if ((trunc_ln22_fu_176_p1 == 1'd0)) begin
            saved_addresses_V_0_d0 = tmp_src_V_fu_154_p1;
        end else begin
            saved_addresses_V_0_d0 = 'bx;
        end
    end else begin
        saved_addresses_V_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1) & (trunc_ln22_fu_176_p1 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1) & (trunc_ln22_fu_176_p1 == 1'd0)))) begin
        saved_addresses_V_0_we0 = 1'b1;
    end else begin
        saved_addresses_V_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_121)) begin
        if ((trunc_ln22_fu_176_p1 == 1'd0)) begin
            saved_addresses_V_1_address0 = zext_ln23_fu_212_p1;
        end else if ((trunc_ln22_fu_176_p1 == 1'd1)) begin
            saved_addresses_V_1_address0 = zext_ln22_fu_190_p1;
        end else begin
            saved_addresses_V_1_address0 = 'bx;
        end
    end else begin
        saved_addresses_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_353)) begin
        if ((trunc_ln31_reg_332 == 1'd0)) begin
            saved_addresses_V_1_address1 = zext_ln32_fu_297_p1;
        end else if ((trunc_ln31_reg_332 == 1'd1)) begin
            saved_addresses_V_1_address1 = zext_ln31_fu_292_p1;
        end else begin
            saved_addresses_V_1_address1 = 'bx;
        end
    end else begin
        saved_addresses_V_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1) & (trunc_ln22_fu_176_p1 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1) & (trunc_ln22_fu_176_p1 == 1'd0)))) begin
        saved_addresses_V_1_ce0 = 1'b1;
    end else begin
        saved_addresses_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (first_load_reg_328 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln31_reg_332 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (first_load_reg_328 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln31_reg_332 == 1'd0)))) begin
        saved_addresses_V_1_ce1 = 1'b1;
    end else begin
        saved_addresses_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_121)) begin
        if ((trunc_ln22_fu_176_p1 == 1'd0)) begin
            saved_addresses_V_1_d0 = {{user_extern_in_TDATA_int_regslice[63:32]}};
        end else if ((trunc_ln22_fu_176_p1 == 1'd1)) begin
            saved_addresses_V_1_d0 = tmp_src_V_fu_154_p1;
        end else begin
            saved_addresses_V_1_d0 = 'bx;
        end
    end else begin
        saved_addresses_V_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1) & (trunc_ln22_fu_176_p1 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1) & (trunc_ln22_fu_176_p1 == 1'd0)))) begin
        saved_addresses_V_1_we0 = 1'b1;
    end else begin
        saved_addresses_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1))) begin
        user_extern_in_TDATA_blk_n = user_extern_in_TVALID_int_regslice;
    end else begin
        user_extern_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1))) begin
        user_extern_in_TREADY_int_regslice = 1'b1;
    end else begin
        user_extern_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (first_load_reg_328_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (first_load_reg_328_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (first_load_reg_328_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (first_load_reg_328_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        user_extern_out_TDATA_blk_n = user_extern_out_TREADY_int_regslice;
    end else begin
        user_extern_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((first_load_reg_328_pp0_iter1_reg == 1'd1)) begin
            user_extern_out_TDATA_int_regslice = 64'd0;
        end else if ((first_load_reg_328_pp0_iter1_reg == 1'd0)) begin
            user_extern_out_TDATA_int_regslice = p_s_fu_316_p3;
        end else begin
            user_extern_out_TDATA_int_regslice = 'bx;
        end
    end else begin
        user_extern_out_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (first_load_reg_328_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (first_load_reg_328_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        user_extern_out_TVALID_int_regslice = 1'b1;
    end else begin
        user_extern_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln885_1_fu_268_p2 = (prev_V + 8'd2);

assign add_ln885_fu_222_p2 = (curr_V + 8'd2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & ((regslice_both_user_extern_out_U_apdone_blk == 1'b1) | ((first_load_reg_328_pp0_iter2_reg == 1'd1) & (user_extern_out_TREADY_int_regslice == 1'b0)) | ((first_load_reg_328_pp0_iter2_reg == 1'd0) & (user_extern_out_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((first_load_reg_328_pp0_iter1_reg == 1'd1) & (user_extern_out_TREADY_int_regslice == 1'b0)) | ((first_load_reg_328_pp0_iter1_reg == 1'd0) & (user_extern_out_TREADY_int_regslice == 1'b0)))) | ((user_extern_in_TVALID_int_regslice == 1'b0) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & ((regslice_both_user_extern_out_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state4_io) | ((first_load_reg_328_pp0_iter2_reg == 1'd1) & (user_extern_out_TREADY_int_regslice == 1'b0)) | ((first_load_reg_328_pp0_iter2_reg == 1'd0) & (user_extern_out_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((1'b1 == ap_block_state3_io) | ((first_load_reg_328_pp0_iter1_reg == 1'd1) & (user_extern_out_TREADY_int_regslice == 1'b0)) | ((first_load_reg_328_pp0_iter1_reg == 1'd0) & (user_extern_out_TREADY_int_regslice == 1'b0)))) | ((user_extern_in_TVALID_int_regslice == 1'b0) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter3 == 1'b1) & ((regslice_both_user_extern_out_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state4_io) | ((first_load_reg_328_pp0_iter2_reg == 1'd1) & (user_extern_out_TREADY_int_regslice == 1'b0)) | ((first_load_reg_328_pp0_iter2_reg == 1'd0) & (user_extern_out_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((1'b1 == ap_block_state3_io) | ((first_load_reg_328_pp0_iter1_reg == 1'd1) & (user_extern_out_TREADY_int_regslice == 1'b0)) | ((first_load_reg_328_pp0_iter1_reg == 1'd0) & (user_extern_out_TREADY_int_regslice == 1'b0)))) | ((user_extern_in_TVALID_int_regslice == 1'b0) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (user_extern_in_TVALID_int_regslice == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_io = (((first_load_reg_328_pp0_iter1_reg == 1'd1) & (user_extern_out_TREADY_int_regslice == 1'b0)) | ((first_load_reg_328_pp0_iter1_reg == 1'd0) & (user_extern_out_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (((first_load_reg_328_pp0_iter1_reg == 1'd1) & (user_extern_out_TREADY_int_regslice == 1'b0)) | ((first_load_reg_328_pp0_iter1_reg == 1'd0) & (user_extern_out_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state4_io = (((first_load_reg_328_pp0_iter2_reg == 1'd1) & (user_extern_out_TREADY_int_regslice == 1'b0)) | ((first_load_reg_328_pp0_iter2_reg == 1'd0) & (user_extern_out_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((regslice_both_user_extern_out_U_apdone_blk == 1'b1) | ((first_load_reg_328_pp0_iter2_reg == 1'd1) & (user_extern_out_TREADY_int_regslice == 1'b0)) | ((first_load_reg_328_pp0_iter2_reg == 1'd0) & (user_extern_out_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_condition_121 = ((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_condition_353 = ((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (first_load_reg_328 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'b0;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign first_load_load_fu_218_p1 = first;

assign lshr_ln1_fu_202_p4 = {{ret_fu_196_p2[7:1]}};

assign lshr_ln_fu_180_p4 = {{curr_V[7:1]}};

assign p_s_fu_316_p3 = {{tmp_dest_V_1_fu_309_p3}, {tmp_src_V_1_fu_302_p3}};

assign ret_1_fu_246_p2 = (prev_V + 8'd1);

assign ret_fu_196_p2 = (curr_V + 8'd1);

assign tmp_dest_V_1_fu_309_p3 = ((trunc_ln31_reg_332_pp0_iter1_reg[0:0] == 1'b1) ? saved_addresses_V_0_q1 : saved_addresses_V_1_q1);

assign tmp_src_V_1_fu_302_p3 = ((trunc_ln31_reg_332_pp0_iter1_reg[0:0] == 1'b1) ? saved_addresses_V_1_q1 : saved_addresses_V_0_q1);

assign tmp_src_V_fu_154_p1 = user_extern_in_TDATA_int_regslice[31:0];

assign trunc_ln22_fu_176_p1 = curr_V[0:0];

assign trunc_ln31_fu_232_p1 = prev_V[0:0];

assign user_extern_in_TREADY = regslice_both_user_extern_in_U_ack_in;

assign user_extern_out_TVALID = regslice_both_user_extern_out_U_vld_out;

assign zext_ln22_fu_190_p1 = lshr_ln_fu_180_p4;

assign zext_ln23_fu_212_p1 = lshr_ln1_fu_202_p4;

assign zext_ln31_fu_292_p1 = lshr_ln2_reg_338;

assign zext_ln32_fu_297_p1 = lshr_ln3_reg_343;

endmodule //saveSrcDest_kernel
