-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity exchangeFivetuple is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    user_extern_in_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    user_extern_in_TVALID : IN STD_LOGIC;
    user_extern_in_TREADY : OUT STD_LOGIC;
    user_extern_out_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    user_extern_out_TVALID : OUT STD_LOGIC;
    user_extern_out_TREADY : IN STD_LOGIC );
end;


architecture behav of exchangeFivetuple is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "exchangeFivetuple_exchangeFivetuple,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu280-fsvh2892-2L-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.000000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=4,HLS_SYN_LUT=47,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal user_extern_in_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal user_extern_out_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_2_fu_105_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp3_fu_95_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_fu_85_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal in_extern_src_V_1_fu_71_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_extern_dst_V_fu_75_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln16_1_fu_115_p6 : STD_LOGIC_VECTOR (103 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_user_extern_in_U_apdone_blk : STD_LOGIC;
    signal user_extern_in_TDATA_int_regslice : STD_LOGIC_VECTOR (127 downto 0);
    signal user_extern_in_TVALID_int_regslice : STD_LOGIC;
    signal user_extern_in_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_user_extern_in_U_ack_in : STD_LOGIC;
    signal regslice_both_user_extern_out_U_apdone_blk : STD_LOGIC;
    signal user_extern_out_TDATA_int_regslice : STD_LOGIC_VECTOR (127 downto 0);
    signal user_extern_out_TVALID_int_regslice : STD_LOGIC;
    signal user_extern_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_user_extern_out_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component exchangeFivetuple_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_user_extern_in_U : component exchangeFivetuple_regslice_both
    generic map (
        DataWidth => 128)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => user_extern_in_TDATA,
        vld_in => user_extern_in_TVALID,
        ack_in => regslice_both_user_extern_in_U_ack_in,
        data_out => user_extern_in_TDATA_int_regslice,
        vld_out => user_extern_in_TVALID_int_regslice,
        ack_out => user_extern_in_TREADY_int_regslice,
        apdone_blk => regslice_both_user_extern_in_U_apdone_blk);

    regslice_both_user_extern_out_U : component exchangeFivetuple_regslice_both
    generic map (
        DataWidth => 128)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => user_extern_out_TDATA_int_regslice,
        vld_in => user_extern_out_TVALID_int_regslice,
        ack_in => user_extern_out_TREADY_int_regslice,
        data_out => user_extern_out_TDATA,
        vld_out => regslice_both_user_extern_out_U_vld_out,
        ack_out => user_extern_out_TREADY,
        apdone_blk => regslice_both_user_extern_out_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, user_extern_in_TVALID_int_regslice, user_extern_out_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (user_extern_out_TREADY_int_regslice = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and ((user_extern_out_TREADY_int_regslice = ap_const_logic_0) or (user_extern_in_TVALID_int_regslice = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, user_extern_in_TVALID_int_regslice, user_extern_out_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (user_extern_out_TREADY_int_regslice = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and ((user_extern_out_TREADY_int_regslice = ap_const_logic_0) or (user_extern_in_TVALID_int_regslice = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, user_extern_in_TVALID_int_regslice, user_extern_out_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (user_extern_out_TREADY_int_regslice = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and ((user_extern_out_TREADY_int_regslice = ap_const_logic_0) or (user_extern_in_TVALID_int_regslice = ap_const_logic_0))));
    end process;


    ap_block_state2_pp0_stage0_iter0_assign_proc : process(user_extern_in_TVALID_int_regslice, user_extern_out_TREADY_int_regslice)
    begin
                ap_block_state2_pp0_stage0_iter0 <= ((user_extern_out_TREADY_int_regslice = ap_const_logic_0) or (user_extern_in_TVALID_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter1_assign_proc : process(user_extern_out_TREADY_int_regslice)
    begin
                ap_block_state3_pp0_stage0_iter1 <= (user_extern_out_TREADY_int_regslice = ap_const_logic_0);
    end process;

    ap_done <= ap_const_logic_0;
    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= ap_const_logic_0;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    in_extern_dst_V_fu_75_p4 <= user_extern_in_TDATA_int_regslice(63 downto 32);
    in_extern_src_V_1_fu_71_p1 <= user_extern_in_TDATA_int_regslice(32 - 1 downto 0);
    or_ln16_1_fu_115_p6 <= ((((tmp_2_fu_105_p4 & tmp3_fu_95_p4) & tmp_s_fu_85_p4) & in_extern_src_V_1_fu_71_p1) & in_extern_dst_V_fu_75_p4);
    tmp3_fu_95_p4 <= user_extern_in_TDATA_int_regslice(79 downto 64);
    tmp_2_fu_105_p4 <= user_extern_in_TDATA_int_regslice(103 downto 96);
    tmp_s_fu_85_p4 <= user_extern_in_TDATA_int_regslice(95 downto 80);

    user_extern_in_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, user_extern_in_TVALID_int_regslice)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            user_extern_in_TDATA_blk_n <= user_extern_in_TVALID_int_regslice;
        else 
            user_extern_in_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    user_extern_in_TREADY <= regslice_both_user_extern_in_U_ack_in;

    user_extern_in_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            user_extern_in_TREADY_int_regslice <= ap_const_logic_1;
        else 
            user_extern_in_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    user_extern_out_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, user_extern_out_TREADY_int_regslice)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            user_extern_out_TDATA_blk_n <= user_extern_out_TREADY_int_regslice;
        else 
            user_extern_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    user_extern_out_TDATA_int_regslice <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln16_1_fu_115_p6),128));
    user_extern_out_TVALID <= regslice_both_user_extern_out_U_vld_out;

    user_extern_out_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            user_extern_out_TVALID_int_regslice <= ap_const_logic_1;
        else 
            user_extern_out_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

end behav;
